development:
  domain: localhost:3000
  user: username
  password: pwd
  
test:
  domain: test.host
  user: username
  password: pwd
  
production:
  domain: example.com
  user: username
  password: pwd